<?php

use App\Models\Tenun;
use Illuminate\Database\Seeder;

class TenunTableSeeder extends Seeder{
  public function run(){

      Tenun::create([
        'nama_tenun' => 'Tenun Flores A',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF000',
        'asal_tenun' => 'Jawa - Bali',
        'img_src' => 'public/img_src/flores_a.jpg'
      ]);

      Tenun::create([
        'nama_tenun' => 'Tenun Flores B',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/flores_b.jpg'
      ]);

      Tenun::create([
        'nama_tenun' => 'Tenun Flores  C',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/flores_c.jpg'
      ]);

      Tenun::create([
          'nama_tenun' => 'Ulos Harungguan',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/harungguan.jpg'
      ]);

      Tenun::create([
          'nama_tenun' => 'Tenun Jogjakarta A',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/jogjakarta_a.jpg'
      ]);

      Tenun::create([
          'nama_tenun' => 'Tenun Jogjakarta B',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/jogjakarta_b.jpg'
      ]);

      Tenun::create([
          'nama_tenun' => 'Tenun Lombok A',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/lombok_a.jpg'
      ]);

      Tenun::create([
          'nama_tenun' => 'Tenun Lombok B',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/lombok_b.jpg'
      ]);



      Tenun::create([
          'nama_tenun' => 'Ulos Sadum',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/sadum.jpg'
      ]);

      Tenun::create([
          'nama_tenun' => 'Ulos Ragiidup',
        'deskripsi_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'sejarah_tenun' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo sollicitudin consequat. Donec sodales ante id leo elementum efficitur. Vestibulum felis justo, pharetra nec pharetra at, semper eget mauris. Integer sit amet dictum libero. Donec at elit ac nisl scelerisque aliquet. Ut a egestas turpis. Quisque porttitor mi eu lobortis auctor. Donec vulputate justo in ipsum porttitor, elementum porttitor odio viverra. Integer eu commodo tellus.

Pellentesque efficitur imperdiet augue, a pulvinar risus feugiat facilisis. Donec porttitor ornare risus. Nunc vel diam tempus, tristique ex vestibulum, lobortis nulla. Nam molestie nisl tellus, ac ullamcorper justo consectetur quis. Vivamus tincidunt varius diam id bibendum. Aenean ac tempus purus. Etiam non posuere nisl. Etiam sodales sodales molestie.

Morbi tempor, dui vel pulvinar eleifend, magna sapien dignissim augue, ornare aliquam enim est at nibh. Integer nibh nibh, egestas vitae mi consequat, varius ultricies velit. Curabitur tincidunt mattis vulputate. Mauris sodales dolor euismod pulvinar aliquet. Nullam quis interdum risus. Vestibulum eu posuere erat. Donec tincidunt imperdiet leo, nec feugiat lacus vestibulum nec. Sed neque mi, efficitur vitae nisl placerat, aliquet mattis nisl. Etiam mollis risus id ligula efficitur, in interdum tellus ornare. Aliquam massa velit, ultricies tempor augue quis, semper hendrerit leo. Praesent volutpat elit in enim eleifend pulvinar. Ut faucibus tortor non mollis varius.

Duis vel dictum mauris, id molestie leo. Nunc elit eros, condimentum eu bibendum ac, pharetra nec turpis. Donec non dolor sapien. Ut vulputate ipsum sapien. Morbi cursus orci consequat mattis venenatis. Maecenas nec sagittis purus. Pellentesque non purus cursus, efficitur ex consectetur, dictum lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tristique lectus quis sapien tristique, sed blandit ligula consectetur. Nunc pretium iaculis lacus id mollis. Maecenas id pulvinar diam.

Donec vel feugiat sapien, eu molestie diam. Vivamus pretium, quam vitae euismod ultrices, dui ante condimentum libero, non egestas lorem arcu et orci. Aenean commodo, tortor vitae molestie lobortis, nisl nulla ultrices lectus, ac iaculis justo enim vitae enim. In sollicitudin interdum leo hendrerit mollis. Duis et facilisis erat, quis porta nisi. Duis et porttitor augue. Proin vulputate venenatis lectus at tempus. Curabitur vel lectus et lorem viverra pellentesque in id tellus. Curabitur congue mauris et sapien malesuada ultrices. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sodales euismod tempus. Nullam fermentum sapien nec mi sagittis, eu egestas arcu facilisis. Nulla at tempor eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis egestas lacus elit, in tincidunt lorem lacinia et.",
        'kegunaan_tenun' => 'Adat - Pernikahan',
        'warna_dominan' => '#FFF500',
        'asal_tenun' => 'Daerah - Lainnya',
        'img_src' => 'public/img_src/ragiidup.jpg'
      ]);
  }
}
